### PR TITLE
Remove unicode patch

### PR DESCRIPTION
**Pull request by goerz**
I just want to see how this behaves in the feedstock repo itself. Maybe
the unicode issue is only present in staged-recipes?

### CODE REVIEW

**Comment by goerz** [comment]
So this looks like it runs through without errors, but that because it's only running the pipeline on Linux. I suppose that makes sense for a pure-Python "noarch" package, although then I'm sure why the original "staged" recipe at https://github.com/conda-forge/staged-recipes/pull/12250 had to run it [on all three platforms](https://github.com/conda-forge/staged-recipes/runs/924623377). The [previous PR for the v0.3.0 release](https://github.com/conda-forge/doctr-versions-menu-feedstock/pull/2) also [only ran on Linux](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=192501&view=results).

Also, I think the unicode error on Windows is only due to the test at
https://github.com/conda-forge/doctr-versions-menu-feedstock/blob/8f53ce4a1e9fd24340c75b470691a42029ea873f/recipe/meta.yaml#L41

This writes unicode to stdout, so I'm not surprised that Windows can't handle it (apart from the fact that not having a UTF8 default locale in 2020 is insane). We don't *really* need that command as a test though, as the `doctr-versions-menu` package itself is pretty thoroughly tested on [Windows with Appveyor](https://ci.appveyor.com/project/goerz/doctr-versions-menu). So, we could probably get rid of that line in `meta.yaml` if it causes problems in the future.

@hhslepicka: Should I merge this in? Not having to deal with the patch file should make updating the feedstock after a release almost trivial, going forward.

**Review by hhslepicka — APPROVED** [review]
@goerz this looks good to me! Since upstream is testing with Windows and AppVeyor it should be safe for us to remove the patch here.
I agree with you on the fact that not supporting unicode is really terrible.
On the point of the feedstock only building/testing with Linux it is due to the `noarch` flag. The staged-recipes on the other hand build for all OSs and that is why I ended up putting the patch.

What happens if an user invokes the `--help` when using Windows? Do they get an error? If yes, should that be handled at the library?

**Comment by goerz** [comment]
I think anyone running the command in a terminal that doesn't support unicode is likely to get an error. On Linux and Mac, UTF8 is the default, so someone would have to go out of their way to change their locale. On Windows, it would probably depend on the version, the terminal emulator that is being used, and the system settings. I've noticed unicode to be more of a problem on Windows CI systems than on actual recent Windows 10 installations that I've used on rare occasions. Generally, I feel like it's to everyone's ultimate benefit if command line software refuses to run in a terminal that doesn't support unicode, just to force the issue, but maybe, in this case, I'll consider making the output of `--help` ASCII-only, in a future version.

**Comment by goerz** [comment]
Just for fun, I tried it on my own Windows installation. In both CMD and Powershell, printing the `--help` output directly  to console works, but piping it into `more` (or a file) fails. If I do
~~~
chcp 65001 & set PYTHONIOENCODING=utf-8
~~~
piping works (not in WSL, though, strangely)

There's also a [general setting in Windows to enable UTF-8 globally](https://answers.microsoft.com/en-us/surface/forum/surfbook-surfaccess/how-to-change-system-locale-in-windows-10-the/d7826ef0-13cd-43ea-8e01-2846d813dfed), which seems to make it work out of the box.

**Pull request merged**
